ERROR - 2025-03-12 15:18:07 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 C:\xampp\htdocs\projects\tcc\Phpigni\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\projects\tcc\Phpigni\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\projects\tcc\Phpigni\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\projects\tcc\Phpigni\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\projects\tcc\Phpigni\app\Controllers\DiarioController.php(25): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\projects\tcc\Phpigni\system\CodeIgniter.php(933): App\Controllers\DiarioController->salvarAnotacao()
#10 C:\xampp\htdocs\projects\tcc\Phpigni\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DiarioController))
#11 C:\xampp\htdocs\projects\tcc\Phpigni\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\projects\tcc\Phpigni\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\projects\tcc\Phpigni\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\projects\tcc\Phpigni\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-03-12 15:18:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: api/salvar-anotacao]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `anotacoes` (`usuario_uid`, `titulo`, `conteudo`, `compartilhada`, `data`, `updated_at`) VALUES (:usuario_uid:, :titulo:, :conteudo:, :compartilhada:, :data:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\DiarioController.php(25): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\DiarioController->salvarAnotacao()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DiarioController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-12 15:18:07 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `anotacoes` (`usuario_uid`, `titulo`, `conteudo`, `compartilhada`, `data`, `updated_at`) VALUES (\'V0Jt8RdVONbd6FnEVxwob3Z45nE3\', \'Minha primeira anotação\', \'Hoje foi um dia produtivo!\', 0, \'2025-03-12 15:18:07\', \'2025-03-12 15:18:07\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `anotacoes` (`usuario_uid`, `titulo`, `conteudo`, `compartilhada`, `data`, `updated_at`) VALUES (\'V0Jt8RdVONbd6FnEVxwob3Z45nE3\', \'Minha primeira anotação\', \'Hoje foi um dia produtivo!\', 0, \'2025-03-12 15:18:07\', \'2025-03-12 15:18:07\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `anotacoes` (`usuario_uid`, `titulo`, `conteudo`, `compartilhada`, `data`, `updated_at`) VALUES (:usuario_uid:, :titulo:, :conteudo:, :compartilhada:, :data:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\DiarioController.php(25): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\DiarioController->salvarAnotacao()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DiarioController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-03-12 15:18:07 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `anotacoes` (`usuario_uid`, `titulo`, `conteudo`, `compartilhada`, `data`, `updated_at`) VALUES (\'V0Jt8RdVONbd6FnEVxwob3Z45nE3\', \'Minha primeira anotação\', \'Hoje foi um dia produtivo!\', 0, \'2025-03-12 15:18:07\', \'2025-03-12 15:18:07\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `anotacoes` (`usuario_uid`, `titulo`, `conteudo`, `compartilhada`, `data`, `updated_at`) VALUES (\'V0Jt8RdVONbd6FnEVxwob3Z45nE3\', \'Minha primeira anotação\', \'Hoje foi um dia produtivo!\', 0, \'2025-03-12 15:18:07\', \'2025-03-12 15:18:07\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `anotacoes` (`usuario_uid`, `titulo`, `conteudo`, `compartilhada`, `data`, `updated_at`) VALUES (\'V0Jt8RdVONbd6FnEVxwob3Z45nE3\', \'Minha primeira anotação\', \'Hoje foi um dia produtivo!\', 0, \'2025-03-12 15:18:07\', \'2025-03-12 15:18:07\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `anotacoes` (`usuario_uid`, `titulo`, `conteudo`, `compartilhada`, `data`, `updated_at`) VALUES (:usuario_uid:, :titulo:, :conteudo:, :compartilhada:, :data:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\DiarioController.php(25): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\DiarioController->salvarAnotacao()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DiarioController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
